name: clean_architecture
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  freezed: ^3.2.3
  get_it: ^8.2.0
  injectable: ^2.1.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  http: ^1.5.0
  objectbox: ^5.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  auto_route: ^10.1.2
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  objectbox_flutter_libs: ^5.0.0
  pinput: ^5.0.2
  intl_phone_field: ^3.2.0
  file_picker: ^10.3.3
  device_info_plus: ^12.2.0
  uuid: ^4.5.1
  
  
  
  

dev_dependencies:
  build_runner: ^2.4.11
  objectbox_generator: ^5.0.0
  auto_route_generator: ^10.2.4
  injectable_generator: ^2.8.1
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
fonts:
    - family: PoppinsBold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: PoppinsBoldItalic
      fonts:
        - asset: fonts/Poppins-BoldItalic.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraBoldItalic
      fonts:
        - asset: fonts/Poppins-ExtraBoldItalic.ttf
    - family: PoppinsMedium
      fonts:
        - asset: fonts/Poppins-Medium.ttf
    - family: PoppinsMediumItalic
      fonts:
        - asset: fonts/Poppins-MediumItalic.ttf
    - family: PoppinsRegular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: PoppinsSemiBoldItalic
      fonts:
        - asset: fonts/Poppins-SemiBoldItalic.ttf
 