name: inspect_connect
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  freezed: ^3.2.3
  get_it: ^9.0.5
  injectable: ^2.1.2
  intl: ^0.20.2
  connectivity_plus: ^7.0.0
  http: ^1.5.0
  objectbox: ^5.0.0
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  path: ^1.9.1
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  auto_route: ^10.1.2
  flutter_svg: ^2.2.1
  objectbox_flutter_libs: ^5.0.0
  intl_phone_field: ^3.2.0
  file_picker: ^10.3.3
  device_info_plus: ^12.2.0
  uuid: ^4.5.1
  image_picker: ^1.2.0
  flutter_stripe: ^12.1.0
  video_player: ^2.10.0
  google_fonts: ^6.3.2
  flutter_dotenv: ^6.0.0
  country_state_city_pro: ^0.0.6
  carousel_slider: ^5.1.1
  flutter_google_places_sdk: ^0.4.2+1
  mime: ^2.0.0
  http_parser: ^4.1.2
  multi_select_flutter: ^4.1.3
  country_picker: ^2.0.27
  country_state_city: ^0.1.6
  dropdown_search: ^6.0.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0


dev_dependencies:
  build_runner: ^2.4.11
  objectbox_generator: ^5.0.0
  auto_route_generator: ^10.2.4
  injectable_generator: ^2.8.1
  json_serializable: ^6.8.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/app_logo.png
    - assets/videos/onboarding_video.mp4
    - .env